export const chatConfig = {
  assistantName: "MattBot",

  maxInputCharacters: 4000,

  maxMessagesPerSession: 8,

  maxOutputTokens: 800,

  rateLimit: {
    requests: 5,
    windowMinutes: 10,
  },

  suggestedPrompts: [
    "How is Matthew a fit for a Technical Program Manager role?",
    "What is Matthew’s experience with cross-functional leadership?",
    "Summarize Matthew’s AI startup experience.",
  ],

  placeholder: "Ask me a question about Matthew's background, or paste a job description here to see how well Matthew matches the requirements.",

  introMessage:
    "Hi, I’m MattBot. Ask me about Matthew’s TPM experience, systems engineering background, AI startup work, or fit for a specific job description.",

  limitReachedMessage:
    "You’ve reached the demo chat limit for this session. Refreshing the page will reset the local demo, but the production version will include server-side abuse protection.",

  mockResponse:
    "This is a preview response. In the next phase, this message will be generated by the OpenAI API using Matthew’s resume, project history, and portfolio context.",
};